service: cinema-app

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  environment:
    NODE_ENV: dev

plugins:
  - serverless-offline
  - serverless-offline-sqs
  - serverless-dynamodb-local

# custom: ${file(./custom.yml)}
custom:
  serverless-offline:
    httpPort: 4000
    websocketPort: 4001
    websocket:
      enabled: true
      port: 4001
      host: localhost

# Import resources for offline use
resources:
  - ${file(./resources/dynamodb.yml)}
  - ${file(./resources/sqs.yml)}

functions:
  ${file(./functions.yml)}