Resources:
  ReserveBookingQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:service}-${self:provider.stage}-reserve-booking
      # Offline SQS will handle these properties automatically
      # VisibilityTimeout and MessageRetentionPeriod are managed by serverless-offline-sqs 