Resources:
  ReserveBookingQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:service}-${self:provider.stage}-reserve-booking
      VisibilityTimeout: 30
      MessageRetentionPeriod: 1209600 # 14 days in seconds 